[project]
name = "mcp-mssql-query"
version = "0.1.0"
description = "mcp server to query MS SQL server"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.12.0",
    "pyodbc>=5.2.0",
    "python-dotenv>=1.1.1",
]